// swift-tools-version: 6.0
import PackageDescription

// This SwiftPM manifest exists ONLY to typecheck/compile the app without full Xcode
// (run `swift build`). The real app is built from Fellow2.xcodeproj (generated by
// XcodeGen from project.yml) once Xcode is installed — that build bundles Info.plist
// + entitlements so EventKit calendar permission works.
let package = Package(
    name: "Fellow2",
    platforms: [.macOS(.v14)],
    targets: [
        .executableTarget(
            name: "Fellow2",
            path: "Fellow2",
            exclude: ["Info.plist", "Fellow2.entitlements"]
        )
    ]
)
